function [BW,maskedImage] = segmentImage(RGB,MASK)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 04-Jun-2019
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Load Mask
BW = MASK;

% Flood fill
row = 166;
column = 146;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Flood fill
row = 167;
column = 143;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 215;
column = 696;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 182;
column = 637;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 258;
column = 731;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 209;
column = 30;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 226;
column = 564;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 211;
column = 578;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 232;
column = 665;
tolerance = 1.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Invert mask
BW = imcomplement(BW);

% Local graph cut
xPos = [18.0897 178.9103 178.9103 18.0897 ];
yPos = [93.4744 93.4744 229.1667 229.1667 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [157.8026 213.0846 213.0846 157.8026 ];
yPos = [125.6385 125.6385 187.9564 187.9564 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [0.5000 67.3410 67.3410 0.5000 ];
yPos = [185.9462 185.9462 238.2128 238.2128 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [416.1205 525.6795 525.6795 416.1205 ];
yPos = [519.6487 519.6487 574.9308 574.9308 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [441.2487 493.5154 493.5154 441.2487 ];
yPos = [488.4897 488.4897 564.8795 564.8795 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [622.1718 784.5000 784.5000 622.1718 ];
yPos = [0.5000 0.5000 239.2179 239.2179 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [529.7000 592.0179 592.0179 529.7000 ];
yPos = [215.0949 215.0949 293.4949 293.4949 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [502.5615 574.9308 574.9308 502.5615 ];
yPos = [195.9974 195.9974 228.1615 228.1615 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [520.6538 564.8795 564.8795 520.6538 ];
yPos = [195.9974 195.9974 266.3564 266.3564 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [309499 310690 313657 315386 317775 ];
backgroundInd = 321873 ;
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [603.0744 658.3564 658.3564 603.0744 ];
yPos = [147.7513 147.7513 198.0077 198.0077 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [124.6333 211.0744 211.0744 124.6333 ];
yPos = [244.2436 244.2436 282.4385 282.4385 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [94328 94329 97854 100793 101381 102557 104321 107261 110203 112555 116671 117260 119612 120788 ];
backgroundInd = 85522 ;
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [509.5974 556.8385 556.8385 509.5974 ];
yPos = [202.0282 202.0282 236.2026 236.2026 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [304208 304213 304216 304218 304806 305394 305987 305988 306575 306576 307143 307144 307731 307745 307748 308320 308325 308334 308337 308911 308921 310103 310104 310676 311272 311859 312445 313623 314211 316567 317151 317155 317741 317742 317743 ];
backgroundInd = [323021 323609 ];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Invert mask
BW = imcomplement(BW);

% Local graph cut
xPos = [557.8436 639.2590 639.2590 557.8436 ];
yPos = [350.7872 350.7872 464.3667 464.3667 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [345007 345008 345009 345012 345013 345594 345595 346181 346764 346766 347346 347347 347349 348519 349103 349104 349105 349687 349689 350271 350273 350855 350856 351438 351440 352020 352023 352024 353190 353191 353193 353195 353765 353767 353768 353770 353771 353774 353776 354351 354352 354933 354935 354936 354938 355519 355520 356103 356105 ];
backgroundInd = [333251 333256 335009 336180 337940 338479 338524 339696 339697 352648 353242 354407 356751 356755 357339 357926 359066 359068 359069 359072 359653 359662 360253 361414 361415 362027 362589 362638 363181 363763 363768 363769 364350 364363 364364 364940 364941 364943 365520 365537 366104 366115 366116 366121 366123 ];
L = superpixels(X,2405,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [561.8641 638.2538 638.2538 561.8641 ];
yPos = [358.8282 358.8282 469.3923 469.3923 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [345578 345580 345587 345590 346750 347334 347916 347919 348503 349088 350847 351433 352603 352606 353777 354361 354947 355531 355532 356704 357281 357282 357283 357284 357287 357290 ];
backgroundInd = [337348 343772 360248 361428 364342 364347 365542 365579 368464 ];
L = superpixels(X,2313,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Erode mask with disk
radius = 2;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Flood fill
row = 410;
column = 596;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 377;
column = 601;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 382;
column = 598;
tolerance = 2.600000e-01;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 132;
column = 247;
tolerance = 7.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Flood fill
row = 216;
column = 613;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 290;
column = 472;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Dilate mask with disk
radius = 3;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1)   = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2:3) = (in(:,:,2:3) + 100) / 200;  % a* and b* range is [-100,100].

end
